SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE users;
TRUNCATE TABLE posts;
TRUNCATE TABLE post_comments;
TRUNCATE TABLE post_votes;
TRUNCATE TABLE tags;
TRUNCATE TABLE tag2post;
TRUNCATE TABLE captcha_codes;
SET FOREIGN_KEY_CHECKS = 1;